<template>
  <div class="flex h-full flex-col">
    <LayoutHeader>
      <template #left-header>
        <div class="text-lg-medium text-ink-gray-9">
          {{ __("Weekly summaries") }}
        </div>
      </template>
      <template #right-header>
        <Button
          variant="ghost"
          :loading="summaries.loading"
          :aria-label="__('Refresh')"
          @click="summaries.reload()"
        >
          <template #icon>
            <LucideRefreshCw class="size-4" aria-hidden="true" />
          </template>
        </Button>
        <Button
          v-if="data?.can_generate"
          variant="solid"
          :label="__('Generate summary')"
          @click="showGenerate = true"
        >
          <template #prefix>
            <LucideSparkles class="size-4" aria-hidden="true" />
          </template>
        </Button>
      </template>
    </LayoutHeader>

    <div class="flex-1 overflow-auto">
      <div class="mx-auto w-full max-w-6xl px-4 py-5 md:px-6">
        <p class="max-w-2xl text-p-sm text-ink-gray-6">
          {{
            __(
              "Every Monday each active customer gets a summary of the previous week's tickets, tasks and project progress. A summary generated by hand covers the 7 days up to that day."
            )
          }}
        </p>

        <!-- Filters -->
        <div
          class="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-3"
          role="group"
          :aria-label="__('Filter summaries')"
        >
          <Link
            v-model="filters.customer"
            doctype="HD Customer"
            :label="__('Customer')"
            :placeholder="__('All customers')"
          />
          <FormControl
            v-model="filters.week"
            type="select"
            :label="__('Period ends in')"
            :options="weekOptions"
          />
          <FormControl
            v-model="filters.kind"
            type="select"
            :label="__('Kind')"
            :options="KIND_OPTIONS"
          />
        </div>
        <div v-if="hasFilters" class="mt-2 flex justify-end">
          <Button variant="ghost" :label="__('Clear filters')" @click="clear">
            <template #prefix>
              <LucideX class="size-4" aria-hidden="true" />
            </template>
          </Button>
        </div>

        <TaskyState
          v-if="summaries.error && !summaries.data"
          class="mt-4"
          :icon="LucideCircleAlert"
          :title="__('Couldn\'t load summaries')"
          :message="loadError"
          error
        >
          <Button :label="__('Retry')" @click="summaries.reload()" />
        </TaskyState>

        <div
          v-else
          class="mt-4 overflow-hidden rounded-lg border border-outline-gray-2 bg-surface-base"
          :aria-busy="summaries.loading"
        >
          <div
            class="hidden gap-4 border-b border-outline-gray-2 bg-surface-gray-1 px-4 py-2 text-xs text-ink-gray-5 md:grid"
            :class="GRID"
            aria-hidden="true"
          >
            <span>{{ __("Customer") }}</span>
            <span>{{ __("Kind") }}</span>
            <span>{{ __("The week in numbers") }}</span>
            <span class="text-right">{{ __("Generated") }}</span>
            <span />
          </div>

          <div v-if="summaries.loading && !summaries.data">
            <div
              v-for="i in 6"
              :key="i"
              class="flex items-center gap-3 border-b border-outline-gray-1 px-4 py-3.5 last:border-b-0"
            >
              <div class="flex flex-1 flex-col gap-2 md:flex-row md:gap-4">
                <div
                  class="h-3.5 w-2/5 animate-pulse rounded bg-surface-gray-2"
                />
                <div
                  class="h-3 w-1/4 animate-pulse rounded bg-surface-gray-2"
                />
              </div>
              <div
                class="hidden h-3 w-16 animate-pulse rounded bg-surface-gray-2 md:block"
              />
            </div>
          </div>

          <TaskyState
            v-else-if="!items.length && hasFilters"
            :icon="LucideNewspaper"
            :title="__('No summaries match these filters')"
            :message="
              __(
                'Try another week or kind, or clear the filters to see every summary you can read.'
              )
            "
          >
            <Button :label="__('Clear filters')" @click="clear" />
          </TaskyState>

          <TaskyState
            v-else-if="!items.length"
            :icon="LucideNewspaper"
            :title="__('No summaries yet')"
            :message="
              __(
                'Summaries of customers whose projects you run show up here after the Monday run, or when you generate one.'
              )
            "
          >
            <Button
              v-if="data?.can_generate"
              variant="solid"
              :label="__('Generate summary')"
              @click="showGenerate = true"
            />
          </TaskyState>

          <!-- one group per period, so summaries of the same customer tell apart -->
          <template v-else>
            <section
              v-for="group in groups"
              :key="group.key"
              :aria-label="group.label"
              class="border-b border-outline-gray-2 last:border-b-0"
            >
              <h2
                class="flex items-center gap-2 border-b border-outline-gray-1 bg-surface-gray-1 px-4 py-1.5 text-sm text-ink-gray-7"
              >
                <LucideCalendarRange
                  class="size-4 text-ink-gray-5"
                  aria-hidden="true"
                />
                <span class="font-mono tabular-nums">{{ group.label }}</span>
                <span class="font-mono text-xs tabular-nums text-ink-gray-5">
                  {{ group.rows.length }}
                </span>
              </h2>
              <ul role="list">
                <li
                  v-for="row in group.rows"
                  :key="row.name"
                  class="border-b border-outline-gray-1 last:border-b-0"
                >
                  <RouterLink
                    :to="{ name: 'WorkSummary', params: { name: row.name } }"
                    class="flex flex-col gap-1.5 px-4 py-3 transition-colors hover:bg-surface-gray-1 focus-visible:bg-surface-gray-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-outline-gray-4 md:grid md:items-center md:gap-4"
                    :class="GRID"
                  >
                    <span class="flex min-w-0 items-center gap-2">
                      <span
                        class="truncate text-base-medium"
                        :class="
                          replaced.has(row.name)
                            ? 'text-ink-gray-6'
                            : 'text-ink-gray-8'
                        "
                      >
                        {{ row.customer }}
                      </span>
                      <TaskyBadge
                        v-if="replaced.has(row.name)"
                        :icon="LucideHistory"
                        :label="__('Older version')"
                        :title="
                          __(
                            'A newer summary of the same customer and period was generated after this one'
                          )
                        "
                      />
                    </span>
                    <span class="flex flex-wrap items-center gap-2 md:contents">
                      <span>
                        <SummaryKindBadge :ai="!!row.generated_by_ai" />
                      </span>
                      <span
                        class="flex min-w-0 flex-wrap items-center gap-x-2 gap-y-1 text-sm tabular-nums text-ink-gray-7"
                      >
                        <template v-if="figures(row).length">
                          <span
                            v-for="figure in figures(row)"
                            :key="figure.key"
                            class="whitespace-nowrap"
                            :class="figure.danger ? 'text-danger' : ''"
                          >
                            <LucideAlarmClock
                              v-if="figure.danger"
                              class="mr-0.5 inline size-3.5 align-[-2px]"
                              aria-hidden="true"
                            />
                            {{ figure.text }}
                          </span>
                        </template>
                        <span v-else class="text-ink-gray-5">
                          {{ __("No figures") }}
                        </span>
                      </span>
                      <span
                        class="font-mono text-xs tabular-nums text-ink-gray-5 md:text-right"
                        :title="dayjs(row.creation).format('D MMM YYYY, HH:mm')"
                      >
                        {{ formatDay(row.creation) }}
                      </span>
                    </span>
                    <LucideChevronRight
                      class="hidden size-4 text-ink-gray-4 md:block"
                      aria-hidden="true"
                    />
                  </RouterLink>
                </li>
              </ul>
            </section>
          </template>
        </div>

        <div v-if="canLoadMore" class="mt-3 flex justify-center">
          <Button
            :label="__('Load more')"
            :loading="summaries.loading"
            @click="limit += PAGE_SIZE"
          />
        </div>
      </div>
    </div>

    <GenerateSummaryDialog
      v-model:open="showGenerate"
      :default-customer="filters.customer"
      @generated="openSummary"
    />
  </div>
</template>

<script setup lang="ts">
import { Link } from "@/components";
import LayoutHeader from "@/components/LayoutHeader.vue";
import TaskyBadge from "@/pages/tasky/components/TaskyBadge.vue";
import TaskyState from "@/pages/tasky/components/TaskyState.vue";
import { __ } from "@/translation";
import { Button, createResource, dayjs, FormControl } from "frappe-ui";
import { computed, reactive, ref, watch } from "vue";
import { RouterLink, useRoute, useRouter } from "vue-router";
import LucideAlarmClock from "~icons/lucide/alarm-clock";
import LucideCalendarRange from "~icons/lucide/calendar-range";
import LucideChevronRight from "~icons/lucide/chevron-right";
import LucideCircleAlert from "~icons/lucide/circle-alert";
import LucideHistory from "~icons/lucide/history";
import LucideNewspaper from "~icons/lucide/newspaper";
import LucideRefreshCw from "~icons/lucide/refresh-cw";
import LucideSparkles from "~icons/lucide/sparkles";
import LucideX from "~icons/lucide/x";
import GenerateSummaryDialog from "./components/GenerateSummaryDialog.vue";
import SummaryKindBadge from "./components/SummaryKindBadge.vue";
import {
  errorText,
  formatDay,
  formatPeriod,
  type SummaryDetail,
  type SummaryList,
} from "./summaryMeta";

type Row = SummaryList["summaries"][number];
type FilterKey = "customer" | "week" | "kind";
const FILTER_KEYS: FilterKey[] = ["customer", "week", "kind"];

const PAGE_SIZE = 20;
// the server caps a page at 100
const MAX_LIMIT = 100;
const WEEKS_SHOWN = 12;
const GRID = "md:grid-cols-[minmax(0,1fr)_5.5rem_minmax(0,18rem)_5.5rem_1rem]";

const KIND_OPTIONS = [
  { label: __("AI and plain"), value: "" },
  { label: __("Written by AI"), value: "ai" },
  { label: __("Plain"), value: "plain" },
];

const route = useRoute();
const router = useRouter();

function queryValue(key: string) {
  const value = route.query[key];
  if (typeof value !== "string") return "";
  // a hand-edited link like ?week=foo would fail on the server and show "Invalid Date"
  return key === "week" && !isCalendarDate(value) ? "" : value;
}

/** A real YYYY-MM-DD date (no dayjs plugin needed). */
function isCalendarDate(value: string) {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
  if (!match) return false;
  const [year, month, day] = match.slice(1).map(Number);
  const date = new Date(Date.UTC(year, month - 1, day));
  return (
    date.getUTCFullYear() === year &&
    date.getUTCMonth() === month - 1 &&
    date.getUTCDate() === day
  );
}

const filters = reactive(
  Object.fromEntries(FILTER_KEYS.map((k) => [k, queryValue(k)])) as Record<
    FilterKey,
    string
  >
);
const hasFilters = computed(() => FILTER_KEYS.some((k) => !!filters[k]));
const limit = ref(PAGE_SIZE);
const showGenerate = ref(false);

function clear() {
  for (const key of FILTER_KEYS) filters[key] = "";
}

// Mondays of the recent weeks; a week matches summaries whose period ends in it
const weekOptions = computed(() => {
  const today = dayjs().startOf("day");
  const monday = today.subtract((today.day() + 6) % 7, "day");
  const options = [{ label: __("Any week"), value: "" }];
  for (let i = 0; i < WEEKS_SHOWN; i++) {
    const start = monday.subtract(i, "week");
    const range = formatPeriod(
      start.format("YYYY-MM-DD"),
      start.add(6, "day").format("YYYY-MM-DD")
    );
    const label =
      i === 0
        ? __("This week ({0})", range)
        : i === 1
        ? __("Last week ({0})", range)
        : range;
    options.push({ label, value: start.format("YYYY-MM-DD") });
  }
  // a shared link may point further back than the list offers
  if (filters.week && !options.some((o) => o.value === filters.week)) {
    const start = dayjs(filters.week);
    options.push({
      label: formatPeriod(
        start.format("YYYY-MM-DD"),
        start.add(6, "day").format("YYYY-MM-DD")
      ),
      value: filters.week,
    });
  }
  return options;
});

const summaries = createResource({
  url: "helpdesk.api.work_summary.get_summaries",
  makeParams: () => ({
    ...Object.fromEntries(FILTER_KEYS.map((k) => [k, filters[k] || undefined])),
    limit: limit.value,
  }),
  auto: true,
});

// keep the filters in the URL so they survive reloads and can be shared
watch(
  () => ({ ...filters }),
  (f) => {
    router.replace({
      query: {
        ...route.query,
        ...Object.fromEntries(FILTER_KEYS.map((k) => [k, f[k] || undefined])),
      },
    });
    limit.value = PAGE_SIZE;
    summaries.reload();
  },
  { deep: true }
);

watch(limit, (value, previous) => {
  if (value > previous) summaries.reload();
});

const data = computed(() => summaries.data as SummaryList | undefined);
const items = computed<Row[]>(() => data.value?.summaries ?? []);

const groups = computed(() => {
  const byPeriod = new Map<
    string,
    { key: string; label: string; rows: Row[] }
  >();
  for (const row of items.value) {
    const key = `${row.period_start}|${row.period_end}`;
    if (!byPeriod.has(key)) {
      byPeriod.set(key, {
        key,
        label: formatPeriod(row.period_start, row.period_end),
        rows: [],
      });
    }
    byPeriod.get(key)!.rows.push(row);
  }
  return [...byPeriod.values()];
});

// newest first, so any later row for the same customer and period was replaced
const replaced = computed(() => {
  const seen = new Set<string>();
  const older = new Set<string>();
  for (const row of items.value) {
    const key = `${row.customer}|${row.period_start}|${row.period_end}`;
    if (seen.has(key)) older.add(row.name);
    seen.add(key);
  }
  return older;
});

function figures(row: Row) {
  const h = row.highlights;
  const list: { key: string; text: string; danger?: boolean }[] = [];
  if (h.tickets_opened != null)
    list.push({
      key: "opened",
      text: __("{0} tickets opened", String(h.tickets_opened)),
    });
  if (h.tickets_resolved != null)
    list.push({
      key: "resolved",
      text: __("{0} resolved", String(h.tickets_resolved)),
    });
  if (h.tasks_completed != null)
    list.push({
      key: "done",
      text: __("{0} tasks done", String(h.tasks_completed)),
    });
  if (h.tasks_overdue)
    list.push({
      key: "overdue",
      text: __("{0} overdue", String(h.tasks_overdue)),
      danger: true,
    });
  return list;
}

const canLoadMore = computed(
  () => items.value.length >= limit.value && limit.value < MAX_LIMIT
);

const loadError = computed(() =>
  errorText(summaries.error, __("Check your connection and try again."))
);

function openSummary(summary: SummaryDetail) {
  router.push({ name: "WorkSummary", params: { name: summary.name } });
}
</script>
